package com.murilloskills.forge112.client.gui;

import com.murilloskills.forge112.MurilloSkillsForge112;
import com.murilloskills.forge112.client.*;
import com.murilloskills.forge112.client.config.*;
import com.murilloskills.forge112.client.gui.*;
import com.murilloskills.forge112.client.input.*;
import com.murilloskills.forge112.client.render.*;
import com.murilloskills.forge112.commands.*;
import com.murilloskills.forge112.config.*;
import com.murilloskills.forge112.data.*;
import com.murilloskills.forge112.dev.*;
import com.murilloskills.forge112.events.*;
import com.murilloskills.forge112.skills.*;
import com.murilloskills.forge112.utils.*;
import static com.murilloskills.forge112.MurilloSkillsForge112.*;
import static com.murilloskills.forge112.client.gui.Forge112UiSupport.*;
import static com.murilloskills.forge112.dev.Forge112SelfTest.*;
import static com.murilloskills.forge112.skills.Forge112Abilities.*;
import static com.murilloskills.forge112.skills.Forge112Passives.*;
import static com.murilloskills.forge112.skills.Forge112TimedEffects.*;
import static com.murilloskills.forge112.utils.Forge112EnvironmentEffects.*;
import static com.murilloskills.forge112.utils.Forge112MiningTools.*;
import static com.murilloskills.forge112.utils.Forge112PlayerServices.*;
import static com.murilloskills.forge112.utils.Forge112SkillMath.*;

import com.google.gson.JsonElement;
import com.google.gson.Gson;
import com.google.gson.GsonBuilder;
import com.google.gson.JsonObject;
import com.google.gson.JsonParser;
import com.murilloskills.core.compat.CrossModCompatRules;
import com.murilloskills.core.config.SkillProgressionConfig;
import com.murilloskills.core.config.SkillType;
import com.murilloskills.core.data.PlayerSkillDataCore;
import com.murilloskills.core.data.SkillStatsCore;
import com.murilloskills.core.data.XpAddResult;
import com.murilloskills.core.io.PlayerSkillJsonCodec;
import net.minecraft.block.Block;
import net.minecraft.block.BlockCrops;
import net.minecraft.block.IGrowable;
import net.minecraft.block.state.IBlockState;
import net.minecraft.client.Minecraft;
import net.minecraft.client.gui.GuiButton;
import net.minecraft.client.gui.GuiMainMenu;
import net.minecraft.client.gui.GuiScreen;
import net.minecraft.client.gui.GuiTextField;
import net.minecraft.client.gui.ScaledResolution;
import net.minecraft.client.renderer.BufferBuilder;
import net.minecraft.client.renderer.GlStateManager;
import net.minecraft.client.renderer.RenderHelper;
import net.minecraft.client.renderer.Tessellator;
import net.minecraft.client.renderer.vertex.DefaultVertexFormats;
import net.minecraft.client.settings.KeyBinding;
import net.minecraft.command.CommandBase;
import net.minecraft.command.CommandException;
import net.minecraft.command.ICommandSender;
import net.minecraft.command.WrongUsageException;
import net.minecraft.enchantment.EnchantmentHelper;
import net.minecraft.entity.Entity;
import net.minecraft.entity.EntityLivingBase;
import net.minecraft.entity.SharedMonsterAttributes;
import net.minecraft.entity.ai.attributes.AttributeModifier;
import net.minecraft.entity.ai.attributes.IAttribute;
import net.minecraft.entity.ai.attributes.IAttributeInstance;
import net.minecraft.entity.item.EntityItem;
import net.minecraft.entity.player.EntityPlayer;
import net.minecraft.entity.player.EntityPlayerMP;
import net.minecraft.entity.projectile.EntityArrow;
import net.minecraft.init.Blocks;
import net.minecraft.init.Items;
import net.minecraft.init.MobEffects;
import net.minecraft.item.Item;
import net.minecraft.item.ItemStack;
import net.minecraft.nbt.NBTTagCompound;
import net.minecraft.potion.PotionEffect;
import net.minecraft.server.MinecraftServer;
import net.minecraft.tileentity.TileEntity;
import net.minecraft.tileentity.TileEntityChest;
import net.minecraft.tileentity.TileEntityMobSpawner;
import net.minecraft.util.DamageSource;
import net.minecraft.util.EnumFacing;
import net.minecraft.util.EnumHand;
import net.minecraft.util.ResourceLocation;
import net.minecraft.util.SoundCategory;
import net.minecraft.init.SoundEvents;
import net.minecraft.util.math.AxisAlignedBB;
import net.minecraft.util.math.BlockPos;
import net.minecraft.util.math.RayTraceResult;
import net.minecraft.util.math.Vec3d;
import net.minecraft.util.text.TextComponentString;
import net.minecraft.world.GameType;
import net.minecraft.world.World;
import net.minecraft.world.WorldSettings;
import net.minecraft.world.WorldType;
import net.minecraft.world.WorldServer;
import net.minecraftforge.client.event.RenderGameOverlayEvent;
import net.minecraftforge.client.event.RenderWorldLastEvent;
import net.minecraftforge.common.MinecraftForge;
import net.minecraftforge.event.entity.EntityJoinWorldEvent;
import net.minecraftforge.event.entity.living.LivingDeathEvent;
import net.minecraftforge.event.entity.living.LivingFallEvent;
import net.minecraftforge.event.entity.living.LivingHurtEvent;
import net.minecraftforge.event.entity.player.AttackEntityEvent;
import net.minecraftforge.event.entity.player.ItemFishedEvent;
import net.minecraftforge.event.entity.player.PlayerEvent;
import net.minecraftforge.event.entity.player.PlayerInteractEvent;
import net.minecraftforge.event.world.BlockEvent;
import net.minecraftforge.fml.client.registry.ClientRegistry;
import net.minecraftforge.fml.common.FMLCommonHandler;
import net.minecraftforge.fml.common.Mod;
import net.minecraftforge.fml.common.Mod.EventHandler;
import net.minecraftforge.fml.common.event.FMLInitializationEvent;
import net.minecraftforge.fml.common.event.FMLPreInitializationEvent;
import net.minecraftforge.fml.common.event.FMLServerStartingEvent;
import net.minecraftforge.fml.common.event.FMLServerStoppingEvent;
import net.minecraftforge.fml.common.eventhandler.Event.Result;
import net.minecraftforge.fml.common.eventhandler.EventPriority;
import net.minecraftforge.fml.common.eventhandler.SubscribeEvent;
import net.minecraftforge.fml.common.gameevent.InputEvent;
import net.minecraftforge.fml.common.gameevent.PlayerEvent.ItemCraftedEvent;
import net.minecraftforge.fml.common.gameevent.PlayerEvent.ItemSmeltedEvent;
import net.minecraftforge.fml.common.gameevent.TickEvent;
import net.minecraftforge.fml.relauncher.Side;
import net.minecraftforge.fml.relauncher.SideOnly;
import org.apache.logging.log4j.LogManager;
import org.apache.logging.log4j.Logger;
import org.lwjgl.input.Keyboard;
import org.lwjgl.input.Mouse;
import org.lwjgl.opengl.GL11;

import java.io.IOException;
import java.nio.charset.StandardCharsets;
import java.lang.reflect.Field;
import java.nio.file.Files;
import java.nio.file.Path;
import java.util.ArrayDeque;
import java.util.ArrayList;
import java.util.Arrays;
import java.util.Collections;
import java.util.EnumMap;
import java.util.HashSet;
import java.util.HashMap;
import java.util.LinkedHashSet;
import java.util.List;
import java.util.Locale;
import java.util.Map;
import java.util.Queue;
import java.util.Random;
import java.util.Set;
import java.util.UUID;

public final class Palette {
    public static final int BG_OVERLAY = 0xF0000000;
    public static final int PANEL_BG = 0xE8141420;
    public static final int PANEL_BG_HEADER = 0xF0181828;
    public static final int PANEL_HIGHLIGHT = 0x20FFFFFF;
    public static final int PANEL_SHADOW = 0x40000000;
    public static final int SECTION_BG = 0xD0181825;
    public static final int SECTION_BG_ACTIVE = 0xE0202030;
    public static final int SECTION_BORDER = 0xFF2A2A3A;
    public static final int DIVIDER_COLOR = 0xFF3A4A5A;
    public static final int TEXT_GOLD = 0xFFFFD700;
    public static final int TEXT_WHITE = 0xFFFFFFFF;
    public static final int TEXT_LIGHT = 0xFFDDDDEE;
    public static final int TEXT_GRAY = 0xFFBBBBCC;
    public static final int TEXT_MUTED = 0xFF666680;
    public static final int TEXT_GREEN = 0xFF32CD32;
    public static final int TEXT_AQUA = 0xFF00DDDD;
    public static final int TEXT_YELLOW = 0xFFFFEE44;
    public static final int TEXT_PURPLE = 0xFFDD88FF;
    public static final int ACCENT_GOLD = 0xFFDDA520;
    public static final int ACCENT_GREEN = 0xFF22AA44;
    public static final int ACCENT_BLUE = 0xFF4488DD;
    public static final int PROGRESS_BAR_EMPTY = 0xFF1A1A25;
    public static final int PROGRESS_BAR_FILL = 0xFF44AA66;
    public static final int PROGRESS_BAR_SHINE = 0x40FFFFFF;
    public static final int CARD_GLOW_ACTIVE = 0x3044FF66;
    public static final int CARD_GLOW_PARAGON = 0x40FFD700;
    public static final int CARD_BG_PENDING = 0xE8181830;
    public static final int CARD_BG_PARAGON = 0xF0201810;
    public static final int CARD_BG_LOCKED = 0xD0101015;
    public static final int CARD_BORDER_LOCKED = 0xFF1A1A20;
    public static final int CARD_BG_SELECTED = 0xE8102018;
    public static final int STATUS_INACTIVE = 0xFFAA0000;
    public static final int STATUS_READY = 0xFF00FF00;
    public static final int STATUS_ACTIVE = 0xFF00AA00;
    public static final int PROGRESS_LOCKED_FILL = 0xFF663344;
    public static final int PROGRESS_LOCKED_SHINE = 0x20FF4444;
    public static final int PROGRESS_MAX_SHINE = 0x60FFFFFF;
    public static final int PERK_CLOSE_MARKER = 0xFFAAAA44;
    public static final int HEADER_GRADIENT_BASE = 0x101018;
    public static final int HEADER_ACCENT_LINE = 0x30FFFFFF;
    public static final int CARD_BG_SUBTLE = 0xC0141420;
    public static final int ALTERNATING_ROW_BG = 0x15FFFFFF;
    public static final int HUD_INDICATOR_BG = 0xC0101018;
    public static final int INFO_BOX_BORDER = 0xFF344050;
    public static final int SYNERGY_BADGE_BG = 0xC0203020;
    public static final int SYNERGY_ACTIVE_BG = 0xE0102418;
    public static final int SYNERGY_ACTIVE_GLOW = 0x6044FF66;
    public static final int BONUS_BAR_BG = 0xAA101018;
    public static final int BONUS_BAR_BORDER_ACTIVE = 0xFF22AA44;
    public static final int BONUS_BAR_BORDER_INACTIVE = 0xFF3A3A4A;
}
