package com.murilloskills.utils;

import net.minecraft.block.BlockState;
import net.minecraft.registry.RegistryKey;
import net.minecraft.registry.tag.BlockTags;
import net.minecraft.server.world.ServerWorld;
import net.minecraft.util.math.BlockPos;
import net.minecraft.world.World;

import java.util.HashMap;
import java.util.HashSet;
import java.util.Iterator;
import java.util.LinkedHashSet;
import java.util.Map;
import java.util.Set;

/**
 * Tracks logs generated by saplings so Farmer double harvest can apply once.
 */
public final class FarmerTreeTracker {
    private static final int HORIZONTAL_SCAN_RADIUS = 8;
    private static final int LOWER_SCAN_RADIUS = 2;
    private static final int UPPER_SCAN_RADIUS = 32;
    private static final int MAX_TRACKED_LOGS_PER_WORLD = 200_000;

    private static final Map<RegistryKey<World>, LinkedHashSet<BlockPos>> GENERATED_LOGS = new HashMap<>();

    private FarmerTreeTracker() {
    }

    public static Set<BlockPos> collectNearbyLogs(ServerWorld world, BlockPos origin) {
        Set<BlockPos> logs = new HashSet<>();
        if (world == null || origin == null) {
            return logs;
        }

        for (BlockPos pos : BlockPos.iterate(
                origin.add(-HORIZONTAL_SCAN_RADIUS, -LOWER_SCAN_RADIUS, -HORIZONTAL_SCAN_RADIUS),
                origin.add(HORIZONTAL_SCAN_RADIUS, UPPER_SCAN_RADIUS, HORIZONTAL_SCAN_RADIUS))) {
            BlockState state = world.getBlockState(pos);
            if (isLog(state)) {
                logs.add(pos.toImmutable());
            }
        }
        return logs;
    }

    public static void markNewGeneratedLogs(ServerWorld world, BlockPos origin, Set<BlockPos> beforeLogs) {
        if (world == null || origin == null) {
            return;
        }

        Set<BlockPos> existingLogs = beforeLogs == null ? Set.of() : beforeLogs;
        LinkedHashSet<BlockPos> trackedLogs = GENERATED_LOGS.computeIfAbsent(world.getRegistryKey(),
                ignored -> new LinkedHashSet<>());

        for (BlockPos pos : BlockPos.iterate(
                origin.add(-HORIZONTAL_SCAN_RADIUS, -LOWER_SCAN_RADIUS, -HORIZONTAL_SCAN_RADIUS),
                origin.add(HORIZONTAL_SCAN_RADIUS, UPPER_SCAN_RADIUS, HORIZONTAL_SCAN_RADIUS))) {
            BlockPos immutablePos = pos.toImmutable();
            if (existingLogs.contains(immutablePos)) {
                continue;
            }
            if (isLog(world.getBlockState(pos))) {
                trackedLogs.add(immutablePos);
            }
        }

        trimTrackedLogs(trackedLogs);
    }

    public static boolean consumeGeneratedLog(ServerWorld world, BlockPos pos, BlockState state) {
        if (world == null || pos == null || !isLog(state)) {
            return false;
        }

        Set<BlockPos> trackedLogs = GENERATED_LOGS.get(world.getRegistryKey());
        return trackedLogs != null && trackedLogs.remove(pos.toImmutable());
    }

    public static boolean isLog(BlockState state) {
        return state != null && state.isIn(BlockTags.LOGS);
    }

    private static void trimTrackedLogs(LinkedHashSet<BlockPos> trackedLogs) {
        if (trackedLogs == null || trackedLogs.size() <= MAX_TRACKED_LOGS_PER_WORLD) {
            return;
        }

        Iterator<BlockPos> iterator = trackedLogs.iterator();
        while (trackedLogs.size() > MAX_TRACKED_LOGS_PER_WORLD && iterator.hasNext()) {
            iterator.next();
            iterator.remove();
        }
    }
}
